# Generated by Django 3.2.16 on 2022-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=3)),
                ('cache', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Intent',
            },
        ),
    ]
