# Generated by Django 3.2.16 on 2022-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_action', '0003_message2whatapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intent',
        ),
        migrations.AlterField(
            model_name='message2whatapp',
            name='to_number',
            field=models.CharField(max_length=50),
        ),
    ]
